### ISSUE TITLE
Multiple errors occurring for new leveling character.

### ISSUE THREAD

**Issue by Ookami313** [Hyphie24/Overachiever#1]
Fan Update 1.1.5 is producing the following errors when I log in. It only seems to be occurring for a new character I just started leveling, none of my current 60s get these errors when I log into them. Thanks.

I'm also getting a bug report error from BugGrabber that states '6x (null)', but no other information is listed. I'm assuming this is happening because of Overachiever 1.1.5 since the previous three errors pertain to that addon.

I posted this to the Overchaiever page, but after updating with two more errors I recieved the site marked it as Spam so I'm unsure if it will stay up or not. I'm posting here just in case, but also on the chance an alert is triggered so the addon can be updated/fixed. Thanks again.

***
1x Overachiever\GameTip.lua:17: Cannot find a library instance of "LibBabble-Inventory-3.0".
[string "=[C]"]: in function `error'
[string "@AchieveIt\libs\LibStub\LibStub.lua"]:38: in function `GetLibrary'
[string "@Overachiever\GameTip.lua"]:17: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBabble-Inventory-3.0"."

***
1x Overachiever_Trade\TradeSkills-Tradeskills.lua:5: Cannot find a library instance of "LibBabble-Inventory-3.0".
[string "=[C]"]: in function `error'
[string "@AchieveIt\libs\LibStub\LibStub.lua"]:38: in function `GetLibrary'
[string "@Overachiever_Trade\TradeSkills-Tradeskills.lua"]:5: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBabble-Inventory-3.0"."

***
1x Overachiever\Overachiever-1.1.5.lua:1337: Usage: GameTooltip:HookScript("frameScriptTypeName", function[, bindingType])
[string "=[C]"]: in function `HookScript'
[string "@Overachiever\Overachiever-1.1.5.lua"]:1337: in function <Overachiever\Overachiever.lua:1256>

Locals:
(*temporary) = GameTooltip {
0 = <userdata>
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
ItemTooltip = <unnamed> {
}
SetHyperlink = <function> defined =[C]:-1
RightEdge = <unnamed> {
}
SetVoidWithdrawalItem = <function> defined =[C]:-1
SetSocketGem = <function> defined =[C]:-1
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
Show = <function> defined =[C]:-1
SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:5833
FadeOut = <function> defined =[C]:-1
SetRecipeReagentItem = <function> defined =[C]:-1
SetBuybackItem = <function> defined =[C]:-1
SetWeeklyReward = <function> defined =[C]:-1
SetMerchantItem = <function> defined =[C]:-1
SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
TopRightCorner = <unnamed> {
}
ttIcon = <unnamed> {
}
GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
SetInventoryItem = <function> defined @Vendor\sys\hook.lua:91
TopEdge = <unnamed> {
}
ttCount = <unnamed> {
}
SetLootRollItem = <function> defined =[C]:-1
SetAuctionSellItem = <function> defined =[C]:-1
SetBagItem = <function> defined @Vendor\sys\hook.lua:91
BottomRightCorner = <unnamed> {
}
SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
LeftEdge = <unnamed> {
}
SetAuctionItem = <function> defined =[C]:-1
SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:5769
textLeft1Font = "GameTooltipHeaderText"
Hide = <function> defined =[C]:-1
SetHeirloomByItemID = <function> defined =[C]:-1
SetCurrencyToken = <function> defined @Altoholic\Services\Tooltip.lua:514
SetGuildBankItem = <function> defined =[C]:-1
updateTooltipTimer = 0.200000
TopLeftCorner = <unnamed> {
}
backdropInfo = <table> {
}
SetOwner = <function> defined =[C]:-1
SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
SetExistingSocketGem = <function> defined =[C]:-1
SetUnitBuff = <function> defined =[C]:-1
TextRight1 = GameTooltipTextRight1 {
}
BottomEdge = <unnamed> {
}
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
SetBackpackToken = <function> defined =[C]:-1
TopOverlay = <unnamed> {
}
GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
SetUnitDebuff = <function> defined =[C]:-1
SetItemByID = <function> defined =[C]:-1
SetTrainerService = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
ttGradient = <unnamed> {
}
SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
SetToyByItemID = <function> defined =[C]:-1
SetMerchantCostItem = <function> defined =[C]:-1
SetVoidDepositItem = <function> defined =[C]:-1
SetVoidItem = <function> defined =[C]:-1
SetInboxItem = <function> defined =[C]:-1
ClearLines = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
BottomLeftCorner = <unnamed> {
}
SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:5850
Center = <unnamed> {
}
OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
SetTradeTargetItem = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetTradePlayerItem = <function> defined =[C]:-1
textRight1Font = "GameTooltipHeaderText"
SetSendMailItem = <function> defined =[C]:-1
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
textLeft2Font = "GameTooltipText"
HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
TextRight2 = GameTooltipTextRight2 {
}
TextLeft2 = GameTooltipTextLeft2 {
}
SetUnitAura = <function> defined =[C]:-1
SetQuestLogItem = <function> defined =[C]:-1
textRight2Font = "GameTool

* Edit: Just finished a portion of the Bastion meta achievement (A Time for Courage) and received the following errors:

1x Overachiever\Overachiever-1.1.5.lua:805: attempt to call field 'IsCriteria' (a nil value)
[string "@Overachiever\Overachiever-1.1.5.lua"]:805: in function <Overachiever\Overachiever.lua:798>
[string "@Overachiever\Overachiever-1.1.5.lua"]:1461: in function <Overachiever\Overachiever.lua:1256>

Locals:
achievementID = 14281
criteriaString = "A Time for Courage"
(*temporary) = nil
(*temporary) = 14281
(*temporary) = "A Time for Courage"
(*temporary) = "attempt to call field 'IsCriteria' (a nil value)"
chatprint = <function> defined @Overachiever\Overachiever.lua:82
L = <table> {
SOUND_GLYPH_DESTROY_MINOR = "Glyph Destroy Minor"
OPT_LABEL_MISC = "Miscellaneous"
OPT_UI_PROGRESSIFOTHERCOMPLETED_TIP = "When the cursor is over a quantity-based achievement (e.g. critera of "Obtain 10 mounts") that was completed but not by the current character, display the current character's progress."
SUGGESTIONS_SHOWHIDDEN_TIP2 = "If you want to see all hidden suggestions regardless of location, enter "|cffffffffhidden|r" into the Location field, above.|n|n|cffffffffShift-right-click|r on an achievement to toggle whether it is hidden."
OPT_SELECTSOUND_TIP2 = "Sounds will only play once every 15 seconds."
SERIESTIP = "Part of a series:"
SEARCH_TYPE_OTHER = "Other"
OPT_ANGLERTIPS = "Fishing node fished?"
OPT_UI_REQUIREDFORMETATIP_TIP = "When the cursor is over an achievement that is required to earn another achievement, display the name of the meta-achievement."
OPT_STARTTOAST_DUNGEON = "Show today's dungeon events"
ACH_TURKEYLURKEY_COMPLETE = "Already feathered"
HOLIDAY_DARKMOONFAIRE = "Darkmoon Faire"
SOUND_BELL_KARA = "Karazhan Bell"
SOUND_BELL_HORDE = "Bell - Horde"
SOUND_SIMON_DING = "Simon Ding"
ACH_RIDE_INCOMPLETE = "Need to ride"
SOUND_ALARM1 = "Alarm Clock 1"
OPT_SELECTSOUND_CHECKCOMBAT_TIP = "Don't play reminder sound from needing to kill a creature while you are in combat with it."
SOUND_HEARTHBIND = "Hearthstone Bind"
OPT_LABEL_ACHFOUR = ""%s," "%s,"|n"%s," "%s""
OPT_SELECTSOUND = "Incomplete Achievement Reminder Sound"
SUGGESTIONS_ZONERENAME_COVENANT_NIGHTFAE = "Covenant (Night Fae)"
SOUND_ENTERQUEUE = "Enter Queue"
SUGGESTIONS_TAB = "Suggestions"
MSG_NOOPEN_LIST = "%s |4achievement:achievements; found:"
SOUND_BELL_NIGHTELF = "Bell - Night Elf"
SOUND_BGTIMER = "Battleground Countdown"
OPT_UI_HOLIDAYNOTICE_TIP2 = "|cffffffffTabs module with Suggestions tab is required.|r"
COMPLETEDATE = "Completed on %2$d/%1$02d/%3$02d"
SUGGESTIONS_DIFFICULTY_HEROIC = "Heroic"
SOUND_AGGRO_PULLED = "Aggro Pulled"
SOUND_BELL_ALLIANCE = "Bell - Alliance"
OPT_AUTOTRACK_CRITERIATOAST_TIP = "When the "Achievement Progress" toast appears, automatically track the achievement (if the tracking limit permits)."
WATCH_COPY_TIP = "When enabled, if you |cffffffffshift+alt+click|r on an achievement on this tab, it will be added to the specified watch list."
PROGRESSIFOTHERCOMPLETED = "%s's Progress:"
SUGGESTIONS_RESULTS_TRADESKILL = "%s: %d |4suggestion:suggestions; found."
OPT_LABEL_ACHFIVE = ""%s," "%s,"|n"%s," "%s"|n"%s""
SOUND_DRUMHIT = "Drum Hit"
HOLIDAY_LOVEISINTHEAIR = "Love is in the Air"
OVERACHIEVER_INSTALLED_TOAST = "OVERACHIEVER INSTALLED!"
OPT_UI_HOLIDAYNOTICE_TIP = "If there is a holiday event today (e.g. Brewfest or Darkmoon Faire), a graphical notice appears next to the achievement UI. Clicking it displays achievements for that event. Put your cursor over it for more details."
SOUND_SIMON_BADPRESS = "Simon Bad Press"
ACH_EATYOURGREENS_COMPLETE = "Already eaten"
SOUND_GLYPH_CREATE_MAJOR = "Glyph Create Major"
OPT_CONSUMEITEMTIPS = "Item consumed?"
EVENTNOTICE_ONGOING = "This event is ongoing."
HOLIDAY_WINTERVEIL = "Feast of Winter Veil"
OPT_PESTCONTROLTIPS = "Pest exterminated?"
HOLIDAY_PIGRIMSBOUNTY = "Pilgrim's Bounty"
ACH_BUNNYMAKER_INCOMPLETE = "Need to use Spring Flowers"
RECENTREMINDERCRITERIA = "Recently spotted objective:"
OPT_CHECKYOURHEADTIPS = "Weighted Jack-o'-Lantern used?"
SEARCH_FULLLIST_TIP = "Include in the search achievements that aren't normally listed in the default UI, such as those exclusive to the opposing faction, unacquired Feats of Strength, etc."
SOUND_BELL_MELLOW = "Mellow Bells"
HOLIDAY_MIDSUMMER = "Midsummer Fire Festival"
SUGGESTIONS_EMPTY_OVERRIDE = "Overachiever has no suggestions for the specified location."
SOUND_QUEST_COMPLETE = "Quest C

***
2x Overachiever\Overachiever-1.1.5.lua:1067: attempt to call field 'GetRecentReminders' (a nil value)
[string "@Overachiever\Overachiever-1.1.5.lua"]:1067: in function <Overachiever\Overachiever.lua:949>
[string "=[C]"]: ?

Locals:
self = AchievementFrameAchievementsContainerButton5 {
0 = <userdata>
glow = AchievementFrameAchievementsContainerButton5Glow {
}
description = AchievementFrameAchievementsContainerButton5Description {
}
tabard = AchievementFrameAchievementsContainerButton5Tabard {
}
shield = AchievementFrameAchievementsContainerButton5Shield {
}
OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
backdropBorderColor = <table> {
}
GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
background = AchievementFrameAchievementsContainerButton5Background {
}
hiddenDescription = AchievementFrameAchievementsContainerButton5HiddenDescription {
}
Desaturate = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:1141
icon = AchievementFrameAchievementsContainerButton5Icon {
}
numLines = 3
tracked = AchievementFrameAchievementsContainerButton5Tracked {
}
id = 15043
ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
element = true
GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
index = 25
check = AchievementFrameAchievementsContainerButton5Check {
}
collapsed = true
reward = AchievementFrameAchievementsContainerButton5Reward {
}
SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
highlight = AchievementFrameAchievementsContainerButton5Highlight {
}
label = AchievementFrameAchievementsContainerButton5Label {
}
dateCompleted = AchievementFrameAchievementsContainerButton5ShieldDateCompleted {
}
Expand = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:1085
Collapse = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:1068
Saturate = <function> defined @Blizzard_AchievementUI\Blizzard_AchievementUI.lua:1108
Center = <unnamed> {
}
guildCornerL = AchievementFrameAchievementsContainerButton5GuildCornerL {
}
backdropInfo = <table> {
}
OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
RightEdge = <unnamed> {
}
guildCornerR = AchievementFrameAchievementsContainerButton5GuildCornerR {
}
BottomEdge = <unnamed> {
}
TopRightCorner = <unnamed> {
}
GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
BottomRightCorner = <unnamed> {
}
BottomLeftCorner = <unnamed> {
}
TopEdge = <unnamed> {
}
TopLeftCorner = <unnamed> {
}
objectives = AchievementFrameAchievementsContainerButton5Objectives {
}
plusMinus = AchievementFrameAchievementsContainerButton5PlusMinus {
}
SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
titleBar = AchievementFrameAchievementsContainerButton5TitleBackground {
}
SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
LeftEdge = <unnamed> {
}
rewardBackground = AchievementFrameAchievementsContainerButton5RewardBackground {
}
}
id = 15043
tipset = 2
guildtip = nil
me = nil
(*temporary) = nil
(*temporary) = 15043
(*temporary) = true
(*temporary) = true
(*temporary) = "attempt to call field 'GetRecentReminders' (a nil value)"
checkGuildMembersTooltip = <function> defined @Overachiever\Overachiever.lua:321
button = AchievementFrameAchievementsContainerButton5 {
0 = <userdata>
glow = AchievementFrameAchievementsContainerButton5Glow {
}
description = AchievementFrameAchievementsContainerButton5Description {
}
tabard = AchievementFrameAchievementsContainerButton5Tabard {
}
shield = AchievementFrameAchievementsContainerButton5Shield {
}
OnBackdropLoaded =

**Comment by Hyphie24** [comment]
Question for you, did you change the name of the Overachiever.lua? I see in the post that there is a file called overachiever-1.1.5.lua. I loaded up an alt and did not receive any errors for the libBabble-inventory-3.0

However, I did update the toc of the other 3 files and will put into the next push. I just want to make sure I didn't miss anything with that lua error

Edit: looks like it's a blizzard thing on that .lua name so ignore that. What did you do to cause those errors specifically?

**Comment by Hyphie24** [comment]
Okay, so I figured out the first 3 errors, it is tied to the lib LibBabble-Inventory-3.0, the toc file wasn't pulling the lib correctly. Instead relying on downloading that specific lib as an outside addon. I have since updated the toc and removed that error. I was able to trouble shoot by deleting any files related to that specific lib and found I had installed it from a prev addon and was not having that error.

Before I make an official pull, can you edit the file Overachiever.toc and add the line in bold, to see if that removes the GameTip.lua, Tradeskill and Hookscript error

libs\TjCalendar.lua
**libs\LibBabble-Inventory-3.0\lib.xml**

localization.lua

**Comment by Ookami313** [comment]
To answer your first question about modifying any of the files, no I did not. I just downloaded the 'master' file from here, unzipped it, and copied all the file folders into my addon directory. Everything seemed fine until I started leveling another alt to 60 yesterday when the errors occurred.

However, I did make the requested .toc modification and when I logged in, at least the first three errors (GameTip, TradeSkill, and Overachiever-1.1.5) did not occur. I just started a new zone, so I can't verify if anything like the last two errors pertaining to the zone completion achievement will happen yet.

Thanks.

**Comment by Hyphie24** [comment]
Awesome, thank you. I figured once I read the log more and started to repeat the errors on my end that I noticed it was a blizzard thing. I will push the new update out. I haven't had the time to get an alt to level through the areas again. Hopefully soon. Thank you again, and if that error does happen, please feel free to post a new issue
