### ISSUE TITLE
Overachiever errors in achievments window on hovering

### ISSUE THREAD

**Issue by VsevolodEpinetov** [Hyphie24/Overachiever#14]
Hi! I am getting errors on last version of overachiever in retail wow. Russian language.

While hovering achievments:
```
Message: Interface\AddOns\Overachiever\Overachiever.lua:954: attempt to call method 'SetBackdropColor' (a nil value)
Time: Sun Feb 20 04:00:28 2022
Count: 195
Stack: Interface\AddOns\Overachiever\Overachiever.lua:954: attempt to call method 'SetBackdropColor' (a nil value)
[string "=[C]"]: in function `SetBackdropColor'
[string "@Interface\AddOns\Overachiever\Overachiever.lua"]:954: in function <Interface\AddOns\Overachiever\Overachiever.lua:949>
[string "=[C]"]: ?

Locals: 
```

While hovering tabs on the right (events):
```
Message: ...nterface\AddOns\Overachiever_Tabs\CalendarNotice.lua:107: attempt to call method 'SetBackdropColor' (a nil value)
Time: Sun Feb 20 04:00:48 2022
Count: 15
Stack: ...nterface\AddOns\Overachiever_Tabs\CalendarNotice.lua:107: attempt to call method 'SetBackdropColor' (a nil value)
[string "=[C]"]: in function `SetBackdropColor'
[string "@Interface\AddOns\Overachiever_Tabs\CalendarNotice.lua"]:107: in function <...nterface\AddOns\Overachiever_Tabs\CalendarNotice.lua:103>

Locals: 
```

**Comment by Hyphie24** [comment]
What version of Overachiever are you running currently? I looked at the error code and for the CalendarNotice.lua line 107 error, that line is no longer in version 1.2.3
I also changed my game to the other text languages to see if I can generate the error and I have yet to run across it

**Comment by VsevolodEpinetov** [comment]
My bad dude, seems like I've been using original author's version, not yours, and that's why I was getting errors. 1.2.3 works perfectly fine.
Sorry for the confusion!

**Comment by Hyphie24** [comment]
No problem, thanks for the follow-up. closing issue

**Comment by kuschelmonster-is-me** [comment]
I was having the same problem (except not using a Russian language) and I just wanted to comment that this helped me immensely. I too was using the original version and having the same error - was driving me mad. This version completely fixed it for me.
