### ISSUE TITLE
Wide button

### ISSUE THREAD

**Issue by Mistrick** [Hyphie24/Overachiever#16]
Can you help with fixing wide button in achievements tab.
I use elvui and addonskins with overachiever skin
https://imgur.com/a/wKLHhaJ

**Comment by Hyphie24** [comment]
I don't use addonskins or elvui, so I don't know what could be causing the button size issue. If you see a LUA error pop up for it, I could look to see what can be edited.

**Comment by Mistrick** [comment]
Don't see any errors. Can show only framestack info.
https://imgur.com/a/NOmHvT8
Found some posts in elvui discord about problem(from 2020 and 2021) but nothing for solving bug.

**Comment by Hyphie24** [comment]
Okay, so I downloaded addonskins, that's the issue. there's a skin file for Overachiever within the addon itself. Disabling Overachiever the arrow is normal, with overachiever by itself without the addonskins arrow is again normal. So I'm in the process of narrowing it down to what that arrow is being altered with and fixing. Hopefully will have something soon

**Comment by Hyphie24** [comment]
Digging more into it, I may have found a fix. If you can try changing line 1487 of the Overachiever.lua main file, will be in addons>Overachiever>Overachiever.lua. change the line to 
AchievementFrameFilterDropDownButton:SetWidth(20)
I played with numbers and that seemed to be a okay width for the button. It doesn't seem to alter the normal version of the addon. If this does indeed work as it should, I will push a new update

**Edit**
If you don't want to edit the raw lua file, or don't have line numbers, I've pushed a alpha update and you can grab the file here https://github.com/Hyphie24/Overachiever/blob/1.2.32/Overachiever/Overachiever.lua

**Comment by Mistrick** [comment]
I use this for square shape
```AchievementFrameFilterDropDownButton:SetWidth(AchievementFrameFilterDropDownButton:GetHeight())```
Looks nice now. Thanks for your work.
![image](https://user-images.githubusercontent.com/4307674/169672519-5dffdd24-e17d-4f60-82ab-78ab58bbbc6b.png)

**Comment by Hyphie24** [comment]
Will change to that instead. Glad to get it working

**Comment by Mistrick** [comment]
I tried commenting out the line with changing the width and got the same result.
Maybe it was fix for something but now don't needed?

**Comment by Hyphie24** [comment]
Possible, but it is working at least
