### ISSUE TITLE
1207: attempt to index field 'OldAchievement' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [Hyphie24/Overachiever#3]
Updated to 1.1.51 and received the following error when I logged in. Thanks.

1x Overachiever\Overachiever-1.1.51.lua:1207: attempt to index field 'OldAchievement' (a nil value)
[string "@Overachiever\Overachiever-1.1.51.lua"]:1207: in function `setUpFunction'
[string "@FrameXML\AlertFrames.lua"]:177: in function `ShowAlert'
[string "@FrameXML\AlertFrames.lua"]:113: in function `AddAlert'
[string "@Overachiever\Overachiever-1.1.51.lua"]:1235: in function `ToastFakeAchievement'
[string "@Overachiever\Overachiever-1.1.51.lua"]:1382: in function <Overachiever\Overachiever.lua:1381>

Locals:
frame = <unnamed> {
 0 = <userdata>
 glow = <unnamed> {
 }
 OnPostShow = <function> defined =[C]:-1
 SetExternallyManagedOutroAnimation = <function> defined =[C]:-1
 Shield = <unnamed> {
 }
 SetAlertContainer = <function> defined =[C]:-1
 Background = <unnamed> {
 }
 Icon = <unnamed> {
 }
 GuildBanner = <unnamed> {
 }
 shine = <unnamed> {
 }
 onClick = <function> defined @Overachiever\Overachiever.lua:1382
 waitAndAnimOut = <unnamed> {
 }
 GuildBorder = <unnamed> {
 }
 id = 5208
 alertContainer = AlertFrame {
 }
 Unlocked = <unnamed> {
 }
 queue = <table> {
 }
 animIn = <unnamed> {
 }
 OnManagedAlertFrameVisibilityChanged = <function> defined =[C]:-1
 GetAlertContainer = <function> defined =[C]:-1
 GuildName = <unnamed> {
 }
 OnPostHide = <function> defined =[C]:-1
 ManagesOwnOutroAnimation = <function> defined =[C]:-1
 delay = 15
 Name = <unnamed> {
 }
}
achievementID = 5208
alreadyEarned = true
name = "OVERACHIEVER UPDATED!"
delay = 15
toptext = nil
onClick = <function> defined @Overachiever\Overachiever.lua:1382
icon = nil
ret = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "AchievementFrame\UI-Achievement-Alert-Background"
(*temporary) = true
(*temporary) = 0
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to index field 'OldAchievement' (a nil value)"
THIS_TITLE = "Overachiever"
AlertFrame_PauseOutAnimation = <function> defined @FrameXML\AlertFrames.lua:729

**Comment by Hyphie24** [comment]
Guess who undid a line while testing and copied over the wrong text and didn't look over it twice...
Fixing now, will redo the .51 update now. Thank you again, I'll leave this open. Just update if the error has been removed. (Also noticed the pull didn't update the toc for the other 3 files so I officially really fixed it this time)

https://github.com/Hyphie24/Overachiever/releases/tag/v1.1.51

**Comment by Ookami313** [comment]
That seems to have done the trick. No errors so far. Thanks again.
