### ISSUE TITLE
Error when loading in / reloading

### ISSUE THREAD

**Issue by Metalkeik** [Hyphie24/Overachiever#8]
Hi, i searched around a bit maybe i could find a working version of overachiever and stumbled upon your version. First of all thank you for trying to fix overachiever, i appreciate it, and sorry for this issue, this happens whether i have other addons enabled or not, so it's definitely problem of this. I tried updating my overachiever from old curseforge version to your overachiever-main then overachiever-1.2, tried clean installing everything separately and i'm always getting these errors when i load in. 

Message: Frame <unnamed>: Unknown script element OnTooltipSetDefaultAnchor
Time: Mon Dec  6 20:27:10 2021
Count: 6

Message: Frame <unnamed>: Unknown script element OnTooltipCleared
Time: Mon Dec  6 20:27:10 2021
Count: 6

Message: Frame <unnamed>: Unknown script element OnTooltipAddMoney
Time: Mon Dec  6 20:27:10 2021
Count: 3

**Comment by Hyphie24** [comment]
Does this error pop up with just Overachiever loaded or is it popping with normal add-ons as well? Doing some quick digging it could be tied to Blizzard Nameplates. I'll take a look and see if I can find that error on my end as well sometime this evening

**Comment by Metalkeik** [comment]
it pops up both with all my addons open and when i have only Overachiever open. You don't have to rush it i just mentioned it :) thanks for fast reply

**Comment by Hyphie24** [comment]
Okay, looking more into it, it's a Blizzard error. It's not being caused by Overachiever at all. So from other addons that have had people post about the same errors, it's a Blizzard issue and to be ignored. Hopefully this helps you out

**Comment by Metalkeik** [comment]
Well if it is a Blizzard issue then nothing we can do about it, thank you and sorry for wrongly posting it as an overachiever issue!

**Comment by gaveer** [comment]
got the same error , i tried to fix and got no errors
@Metalkeik  check this 
https://github.com/Hyphie24/Overachiever/pull/10

**Comment by Metalkeik** [comment]
yes! that seems to have fixed the problem, no LUA errors at all for this. I'm super impressed on how you imagined to fix this.

**Comment by Hyphie24** [comment]
Great to hear, I'll verify and push the pull for the build this evening. I still hadn't seen the errors on my side, but it could just be addon for me blocking it

**Comment by Hyphie24** [comment]
Further update, so in looking deeper into Gaveer's pull. I had added 1 word to a line of code ",GameTooltipTemplate" to line 834 of build.lua and that was causing the frame error. I must've added that as a temp fix to another issue and never removed it. Removing that one instance removed the 3 frame errors. I'll push the new update anyways (the frame addition isn't needed for this instance and the toc for some of them aren't necessary for the .5 build, but I'll still update it) Thank you again!
